### ISSUE TITLE
models/artist.js line 11: 

### ISSUE THREAD

**Issue by kylegorjanc** [kylegorjanc/museumr_awesome#4]
'paintings' is listed by the nodemon server as an unexpected identifier.

**Comment by cyrus-shahrivar** [comment]
NOT COOL :(

**Comment by kylegorjanc** [comment]
It appear that you have missed a comma on line 10, genius.  :dancers:

**Comment by cyrus-shahrivar** [comment]
FIX IT YOURSELF!

**Comment by kylegorjanc** [comment]
copy. :cry:
